---
- hosts: client
  gather_facts: false
  become: true
  tasks:
    - name: add user borg
      ansible.builtin.user:
        name: borg
        generate_ssh_key: true
        ssh_key_bits: 4096
        ssh_key_type: "ed25519"
      notify:
        - fetch client public ssh key
    
  handlers:
    - name: fetch client public ssh key
      fetch:
        src: /home/borg/.ssh/id_ed25519.pub
        dest: /tmp/
        flat: true


- name: Установка публичного ключа на backupserver
  hosts: backupserver
  become: yes

  tasks:
    - name: add user borg
      ansible.builtin.user:
        name: borg
    
    - name: Установка публичного ключа на backupserver
      copy:
       src: /tmp/id_ed25519.pub
       dest: /tmp/
      notify:
        - set authorized_key

  handlers:
  - name: set authorized_key
    authorized_key:
      user: borg
      key: "{{ lookup('file', '/tmp/id_ed25519.pub') }}"


- name: setup borg client
  hosts: client
  become: true

  tasks:
    - name: update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 86400

    - name: install required
      apt:
        name: borgbackup
        state: present


- name: setup borg server
  hosts: backupserver
  become: true

  vars:
    - BACKUP_DIR: '/var/backup'
    - MOUNT_DISK: '/dev/sda'

  tasks:
    - name: update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 86400

    - name: install required
      apt:
        name: borgbackup
        state: present

    - name: create backup directory
      file:
        path: "{{ BACKUP_DIR }}"
        owner: borg
        group: borg
        state: directory
    
    - name: prepare disk for mount
      shell: |
        if [ $(mount | grep -e 'sda\s' | wc -l) -eq 0 ]
        then
          dd if=/dev/zero of="{{ MOUNT_DISK }}" bs=1M
          mkfs.ext4 "{{ MOUNT_DISK }}"
        fi
      notify:
        - mount backup

  handlers:
    - name: mount backup
      mount:
        path: "{{ BACKUP_DIR }}"
        src: "{{ MOUNT_DISK }}"
        fstype: ext4
        state: mounted

- name: setup borg client 
  vars: 
    - ENCRIPTION_KEY: ''
