---
- name: Создание пользователя borg
  hosts: web
  become: yes

  tasks:
    - name: add user borg
      ansible.builtin.user:
        name: borg
        shell: /bin/bash

- name: Генерация и установка ключей на client и backupserver
  hosts: client
  become: yes

  tasks:
    - name: Генерация ключей ed25519
      community.crypto.openssh_keypair:
        path: "/home/borg/.ssh/id_ed25519"
        type: "ed25519"
        size: 4096

    - name: Копирование приватного ключа на backupserver
      copy:
        src: "/home/borg/.ssh/id_ed25519"
        dest: "/home/borg/.ssh/"
        mode: 0600
      delegate_to: backupserver


- name: Установка публичного ключа на client
  hosts: client
  become: yes


  tasks:
    - name: Установка публичного ключа на client
      authorized_key:
        user: borg
        key: "{{ lookup('file', '/home/borg/.ssh/id_ed25519.pub') }}"
        path: "/home/borg/.ssh/authorized_keys"



- name: setup borg
  hosts: client
  become: true

  tasks:
    - name: create backup directory
      ansible.builtin.file:
        path: "{{ BACKUP_DIR }}"
        owner: borg
        group: borg
        state: directory
  
  vars:
    - BACKUP_DIR: '/var/backup'
